/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as BrokersRouteImport } from './routes/brokers'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SyntheticsRouteImport } from './routes/synthetics'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAiStrategyRouteImport } from './routes/api/ai/strategy'
import { Route as ApiDerivTokenRouteImport } from './routes/api/deriv/token'
import { Route as AuthDerivCallbackRouteImport } from './routes/auth/deriv/callback'
import { Route as ApiAuthDerivCallbackRouteImport } from './routes/api/auth/deriv/callback'
import { Route as ApiAuthDerivStartRouteImport } from './routes/api/auth/deriv/start'
import { Route as ApiV1AuthConnectBrokerRouteImport } from './routes/api/v1/auth/connect-broker'
import { Route as ApiV1BrokerServersRouteImport } from './routes/api/v1/broker/servers'
import { Route as ApiV1BrokerStreamRouteImport } from './routes/api/v1/broker/stream'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokersRoute = BrokersRouteImport.update({
  id: '/brokers',
  path: '/brokers',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SyntheticsRoute = SyntheticsRouteImport.update({
  id: '/synthetics',
  path: '/synthetics',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiStrategyRoute = ApiAiStrategyRouteImport.update({
  id: '/api/ai/strategy',
  path: '/api/ai/strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDerivTokenRoute = ApiDerivTokenRouteImport.update({
  id: '/api/deriv/token',
  path: '/api/deriv/token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDerivCallbackRoute = AuthDerivCallbackRouteImport.update({
  id: '/auth/deriv/callback',
  path: '/auth/deriv/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDerivCallbackRoute = ApiAuthDerivCallbackRouteImport.update({
  id: '/api/auth/deriv/callback',
  path: '/api/auth/deriv/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDerivStartRoute = ApiAuthDerivStartRouteImport.update({
  id: '/api/auth/deriv/start',
  path: '/api/auth/deriv/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthConnectBrokerRoute = ApiV1AuthConnectBrokerRouteImport.update({
  id: '/api/v1/auth/connect-broker',
  path: '/api/v1/auth/connect-broker',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1BrokerServersRoute = ApiV1BrokerServersRouteImport.update({
  id: '/api/v1/broker/servers',
  path: '/api/v1/broker/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1BrokerStreamRoute = ApiV1BrokerStreamRouteImport.update({
  id: '/api/v1/broker/stream',
  path: '/api/v1/broker/stream',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backtest': typeof BacktestRoute
  '/brokers': typeof BrokersRoute
  '/calculator': typeof CalculatorRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/synthetics': typeof SyntheticsRoute
  '/terminal': typeof TerminalRoute
  '/api/chat': typeof ApiChatRoute
  '/api/ai/strategy': typeof ApiAiStrategyRoute
  '/api/deriv/token': typeof ApiDerivTokenRoute
  '/auth/deriv/callback': typeof AuthDerivCallbackRoute
  '/api/auth/deriv/callback': typeof ApiAuthDerivCallbackRoute
  '/api/auth/deriv/start': typeof ApiAuthDerivStartRoute
  '/api/v1/auth/connect-broker': typeof ApiV1AuthConnectBrokerRoute
  '/api/v1/broker/servers': typeof ApiV1BrokerServersRoute
  '/api/v1/broker/stream': typeof ApiV1BrokerStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backtest': typeof BacktestRoute
  '/brokers': typeof BrokersRoute
  '/calculator': typeof CalculatorRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/synthetics': typeof SyntheticsRoute
  '/terminal': typeof TerminalRoute
  '/api/chat': typeof ApiChatRoute
  '/api/ai/strategy': typeof ApiAiStrategyRoute
  '/api/deriv/token': typeof ApiDerivTokenRoute
  '/auth/deriv/callback': typeof AuthDerivCallbackRoute
  '/api/auth/deriv/callback': typeof ApiAuthDerivCallbackRoute
  '/api/auth/deriv/start': typeof ApiAuthDerivStartRoute
  '/api/v1/auth/connect-broker': typeof ApiV1AuthConnectBrokerRoute
  '/api/v1/broker/servers': typeof ApiV1BrokerServersRoute
  '/api/v1/broker/stream': typeof ApiV1BrokerStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backtest': typeof BacktestRoute
  '/brokers': typeof BrokersRoute
  '/calculator': typeof CalculatorRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/synthetics': typeof SyntheticsRoute
  '/terminal': typeof TerminalRoute
  '/api/chat': typeof ApiChatRoute
  '/api/ai/strategy': typeof ApiAiStrategyRoute
  '/api/deriv/token': typeof ApiDerivTokenRoute
  '/auth/deriv/callback': typeof AuthDerivCallbackRoute
  '/api/auth/deriv/callback': typeof ApiAuthDerivCallbackRoute
  '/api/auth/deriv/start': typeof ApiAuthDerivStartRoute
  '/api/v1/auth/connect-broker': typeof ApiV1AuthConnectBrokerRoute
  '/api/v1/broker/servers': typeof ApiV1BrokerServersRoute
  '/api/v1/broker/stream': typeof ApiV1BrokerStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backtest'
    | '/brokers'
    | '/calculator'
    | '/login'
    | '/sitemap.xml'
    | '/synthetics'
    | '/terminal'
    | '/api/chat'
    | '/api/ai/strategy'
    | '/api/deriv/token'
    | '/auth/deriv/callback'
    | '/api/auth/deriv/callback'
    | '/api/auth/deriv/start'
    | '/api/v1/auth/connect-broker'
    | '/api/v1/broker/servers'
    | '/api/v1/broker/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backtest'
    | '/brokers'
    | '/calculator'
    | '/login'
    | '/sitemap.xml'
    | '/synthetics'
    | '/terminal'
    | '/api/chat'
    | '/api/ai/strategy'
    | '/api/deriv/token'
    | '/auth/deriv/callback'
    | '/api/auth/deriv/callback'
    | '/api/auth/deriv/start'
    | '/api/v1/auth/connect-broker'
    | '/api/v1/broker/servers'
    | '/api/v1/broker/stream'
  id:
    | '__root__'
    | '/'
    | '/backtest'
    | '/brokers'
    | '/calculator'
    | '/login'
    | '/sitemap.xml'
    | '/synthetics'
    | '/terminal'
    | '/api/chat'
    | '/api/ai/strategy'
    | '/api/deriv/token'
    | '/auth/deriv/callback'
    | '/api/auth/deriv/callback'
    | '/api/auth/deriv/start'
    | '/api/v1/auth/connect-broker'
    | '/api/v1/broker/servers'
    | '/api/v1/broker/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BacktestRoute: typeof BacktestRoute
  BrokersRoute: typeof BrokersRoute
  CalculatorRoute: typeof CalculatorRoute
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SyntheticsRoute: typeof SyntheticsRoute
  TerminalRoute: typeof TerminalRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiAiStrategyRoute: typeof ApiAiStrategyRoute
  ApiDerivTokenRoute: typeof ApiDerivTokenRoute
  AuthDerivCallbackRoute: typeof AuthDerivCallbackRoute
  ApiAuthDerivCallbackRoute: typeof ApiAuthDerivCallbackRoute
  ApiAuthDerivStartRoute: typeof ApiAuthDerivStartRoute
  ApiV1AuthConnectBrokerRoute: typeof ApiV1AuthConnectBrokerRoute
  ApiV1BrokerServersRoute: typeof ApiV1BrokerServersRoute
  ApiV1BrokerStreamRoute: typeof ApiV1BrokerStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brokers': {
      id: '/brokers'
      path: '/brokers'
      fullPath: '/brokers'
      preLoaderRoute: typeof BrokersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/synthetics': {
      id: '/synthetics'
      path: '/synthetics'
      fullPath: '/synthetics'
      preLoaderRoute: typeof SyntheticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/strategy': {
      id: '/api/ai/strategy'
      path: '/api/ai/strategy'
      fullPath: '/api/ai/strategy'
      preLoaderRoute: typeof ApiAiStrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deriv/token': {
      id: '/api/deriv/token'
      path: '/api/deriv/token'
      fullPath: '/api/deriv/token'
      preLoaderRoute: typeof ApiDerivTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/deriv/callback': {
      id: '/auth/deriv/callback'
      path: '/auth/deriv/callback'
      fullPath: '/auth/deriv/callback'
      preLoaderRoute: typeof AuthDerivCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/deriv/callback': {
      id: '/api/auth/deriv/callback'
      path: '/api/auth/deriv/callback'
      fullPath: '/api/auth/deriv/callback'
      preLoaderRoute: typeof ApiAuthDerivCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/deriv/start': {
      id: '/api/auth/deriv/start'
      path: '/api/auth/deriv/start'
      fullPath: '/api/auth/deriv/start'
      preLoaderRoute: typeof ApiAuthDerivStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/connect-broker': {
      id: '/api/v1/auth/connect-broker'
      path: '/api/v1/auth/connect-broker'
      fullPath: '/api/v1/auth/connect-broker'
      preLoaderRoute: typeof ApiV1AuthConnectBrokerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/broker/servers': {
      id: '/api/v1/broker/servers'
      path: '/api/v1/broker/servers'
      fullPath: '/api/v1/broker/servers'
      preLoaderRoute: typeof ApiV1BrokerServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/broker/stream': {
      id: '/api/v1/broker/stream'
      path: '/api/v1/broker/stream'
      fullPath: '/api/v1/broker/stream'
      preLoaderRoute: typeof ApiV1BrokerStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BacktestRoute: BacktestRoute,
  BrokersRoute: BrokersRoute,
  CalculatorRoute: CalculatorRoute,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SyntheticsRoute: SyntheticsRoute,
  TerminalRoute: TerminalRoute,
  ApiChatRoute: ApiChatRoute,
  ApiAiStrategyRoute: ApiAiStrategyRoute,
  ApiDerivTokenRoute: ApiDerivTokenRoute,
  AuthDerivCallbackRoute: AuthDerivCallbackRoute,
  ApiAuthDerivCallbackRoute: ApiAuthDerivCallbackRoute,
  ApiAuthDerivStartRoute: ApiAuthDerivStartRoute,
  ApiV1AuthConnectBrokerRoute: ApiV1AuthConnectBrokerRoute,
  ApiV1BrokerServersRoute: ApiV1BrokerServersRoute,
  ApiV1BrokerStreamRoute: ApiV1BrokerStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
